repos:

#- repo: https://github.com/psf/black
#  rev: 19.10b0
#  hooks:
#  - id: black
#    language_version: python3
#    args: ['--line-length=120']

#- repo: https://github.com/miki725/importanize
#  rev: '0.7'
#  hooks:
#  - id: importanize
#    language_version: python3

- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
  - id: docformatter

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
    -   id: autopep8

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.6.0]
        args: ['--ignore=W293,W503,E203,F401,F403']

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/aducourthial/advestis_hooks
    rev: v2.1
    hooks:
    -   id: doctester

#Commit message part:

-   repo: https://github.com/aducourthial/advestis_hooks
    rev: v2.1
    hooks:
    -   id: format_check
        stages: [commit-msg]
